version: "3.8"

services:
  db:
    container_name: awarehouse-db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: awarehouse
      POSTGRES_USER: awarehouse
      POSTGRES_PASSWORD: awarehouse
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - "8092:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    command: start-dev
  selenium-hub:
    image: selenium/standalone-chrome
    shm_size: 256m
    ports:
       - "4444:4444"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  db:
    driver: local
