version: "3.8"

services:
  db:
    container_name: awarehouse-db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: awarehouse
      POSTGRES_USER: awarehouse
      POSTGRES_PASSWORD: awarehouse
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - "8092:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    command: start-dev
volumes:
  db:
    driver: local
